import React, { Component } from 'react';
import { ResponsiveScatterPlot } from '@nivo/scatterplot';

class PopGrowthVsFossilPower extends Component {
	render(){
		return (
    	<ResponsiveScatterPlot
        data={
		[
		{ "id": "Afghanistan", "data": [{"x":2.36,"y":14}]},
		{ "id": "Albania", "data": [{"x":0.31,"y":5.2}]},
		{ "id": "Algeria", "data": [{"x":1.7,"y":97.9}]},
		{ "id": "American Samoa", "data": [{"x":-1.3,"y":100}]},
		{ "id": "Andorra", "data": [{"x":0.03,"y":61.3}]},
		{ "id": "Angola", "data": [{"x":3.52,"y":45.2}]},
		{ "id": "Antigua and Barbuda", "data": [{"x":1.21,"y":96.6}]},
		{ "id": "Argentina", "data": [{"x":0.91,"y":62.8}]},
		{ "id": "Armenia", "data": [{"x":-0.21,"y":58.8}]},
		{ "id": "Aruba", "data": [{"x":1.27,"y":87.2}]},
		{ "id": "Australia", "data": [{"x":1.03,"y":72.9}]},
		{ "id": "Austria", "data": [{"x":0.47,"y":29}]},
		{ "id": "Azerbaijan", "data": [{"x":0.87,"y":84.5}]},
		{ "id": "Bahamas, The", "data": [{"x":0.81,"y":99.8}]},
		{ "id": "Bahrain", "data": [{"x":2.26,"y":99.8}]},
		{ "id": "Bangladesh", "data": [{"x":1.04,"y":96.6}]},
		{ "id": "Barbados", "data": [{"x":0.28,"y":89.9}]},
		{ "id": "Belarus", "data": [{"x":-0.22,"y":99.2}]},
		{ "id": "Belgium", "data": [{"x":0.7,"y":34.8}]},
		{ "id": "Belize", "data": [{"x":1.8,"y":52.4}]},
		{ "id": "Benin", "data": [{"x":2.71,"y":97.2}]},
		{ "id": "Bermuda", "data": [{"x":0.45,"y":100}]},
		{ "id": "Bhutan", "data": [{"x":1.07,"y":1}]},
		{ "id": "Bolivia", "data": [{"x":1.51,"y":68.1}]},
		{ "id": "Bosnia and Herzegovina", "data": [{"x":-0.16,"y":41.6}]},
		{ "id": "Botswana", "data": [{"x":1.55,"y":98.5}]},
		{ "id": "Brazil", "data": [{"x":0.73,"y":3.1}]},
		{ "id": "British Virgin Islands", "data": [{"x":2.25,"y":65.8}]},
		{ "id": "Brunei", "data": [{"x":1.57,"y":99.9}]},
		{ "id": "Bulgaria", "data": [{"x":-0.61,"y":45}]},
		{ "id": "Burkina Faso", "data": [{"x":3,"y":86.9}]},
		{ "id": "Burma", "data": [{"x":0.91,"y":33.9}]},
		{ "id": "Burundi", "data": [{"x":3.25,"y":13.2}]},
		{ "id": "Cabo Verde", "data": [{"x":1.33,"y":76.8}]},
		{ "id": "Cambodia", "data": [{"x":1.52,"y":37.6}]},
		{ "id": "Cameroon", "data": [{"x":2.56,"y":52.9}]},
		{ "id": "Canada", "data": [{"x":0.73,"y":26.3}]},
		{ "id": "Cayman Islands", "data": [{"x":2.01,"y":100}]},
		{ "id": "Central African Republic", "data": [{"x":2.12,"y":43.2}]},
		{ "id": "Chad", "data": [{"x":1.86,"y":100}]},
		{ "id": "Chile", "data": [{"x":0.77,"y":60.8}]},
		{ "id": "China", "data": [{"x":0.41,"y":64}]},
		{ "id": "Colombia", "data": [{"x":0.99,"y":28.1}]},
		{ "id": "Comoros", "data": [{"x":1.64,"y":96.2}]},
		{ "id": "Congo, Democratic Republic of the", "data": [{"x":2.37,"y":1.3}]},
		{ "id": "Congo, Republic of the", "data": [{"x":2.11,"y":61.7}]},
		{ "id": "Cook Islands", "data": [{"x":-2.79,"y":80}]},
		{ "id": "Costa Rica", "data": [{"x":1.16,"y":21}]},
		{ "id": "Cote d'Ivoire", "data": [{"x":1.84,"y":66.9}]},
		{ "id": "Croatia", "data": [{"x":-0.5,"y":42.5}]},
		{ "id": "Cuba", "data": [{"x":-0.29,"y":90.6}]},
		{ "id": "Cyprus", "data": [{"x":1.32,"y":87.4}]},
		{ "id": "Czechia", "data": [{"x":0.12,"y":56.6}]},
		{ "id": "Denmark", "data": [{"x":0.22,"y":48.1}]},
		{ "id": "Djibouti", "data": [{"x":2.16,"y":100}]},
		{ "id": "Dominica", "data": [{"x":0.18,"y":60.2}]},
		{ "id": "Dominican Republic", "data": [{"x":1.18,"y":80.8}]},
		{ "id": "Ecuador", "data": [{"x":1.28,"y":13.2}]},
		{ "id": "Egypt", "data": [{"x":2.45,"y":90.5}]},
		{ "id": "El Salvador", "data": [{"x":0.25,"y":41.4}]},
		{ "id": "Equatorial Guinea", "data": [{"x":2.44,"y":55.1}]},
		{ "id": "Eritrea", "data": [{"x":0.85,"y":98.6}]},
		{ "id": "Estonia", "data": [{"x":-0.57,"y":85}]},
		{ "id": "Ethiopia", "data": [{"x":2.85,"y":7.5}]},
		{ "id": "European Union", "data": [{"x":0.23,"y":43.6}]},
		{ "id": "Falkland Islands (Islas Malvinas)", "data": [{"x":0.01,"y":90}]},
		{ "id": "Faroe Islands", "data": [{"x":0.55,"y":50.1}]},
		{ "id": "Fiji", "data": [{"x":0.6,"y":36}]},
		{ "id": "Finland", "data": [{"x":0.36,"y":21.2}]},
		{ "id": "France", "data": [{"x":0.39,"y":16.1}]},
		{ "id": "French Polynesia", "data": [{"x":0.88,"y":71.1}]},
		{ "id": "Gabon", "data": [{"x":1.92,"y":50.7}]},
		{ "id": "Gambia, The", "data": [{"x":2.05,"y":100}]},
		{ "id": "Georgia", "data": [{"x":-0.02,"y":36.2}]},
		{ "id": "Germany", "data": [{"x":-0.16,"y":42.6}]},
		{ "id": "Ghana", "data": [{"x":2.17,"y":57.8}]},
		{ "id": "Gibraltar", "data": [{"x":0.23,"y":100}]},
		{ "id": "Greece", "data": [{"x":-0.06,"y":56.8}]},
		{ "id": "Greenland", "data": [{"x":-0.03,"y":51.3}]},
		{ "id": "Grenada", "data": [{"x":0.44,"y":98}]},
		{ "id": "Guam", "data": [{"x":0.26,"y":100}]},
		{ "id": "Guatemala", "data": [{"x":1.75,"y":57.9}]},
		{ "id": "Guinea", "data": [{"x":2.61,"y":50}]},
		{ "id": "Guinea-Bissau", "data": [{"x":1.86,"y":100}]},
		{ "id": "Guyana", "data": [{"x":0.32,"y":86.8}]},
		{ "id": "Haiti", "data": [{"x":1.34,"y":80.9}]},
		{ "id": "Honduras", "data": [{"x":1.6,"y":45.6}]},
		{ "id": "Hong Kong", "data": [{"x":0.32,"y":84}]},
		{ "id": "Hungary", "data": [{"x":-0.25,"y":64.5}]},
		{ "id": "Iceland", "data": [{"x":1.13,"y":4.2}]},
		{ "id": "India", "data": [{"x":1.17,"y":71.5}]},
		{ "id": "Indonesia", "data": [{"x":0.86,"y":88.5}]},
		{ "id": "Iran", "data": [{"x":1.24,"y":83.2}]},
		{ "id": "Iraq", "data": [{"x":2.55,"y":87.3}]},
		{ "id": "Ireland", "data": [{"x":1.15,"y":68.1}]},
		{ "id": "Israel", "data": [{"x":1.51,"y":95.5}]},
		{ "id": "Italy", "data": [{"x":0.19,"y":52.8}]},
		{ "id": "Jamaica", "data": [{"x":0.68,"y":85.5}]},
		{ "id": "Japan", "data": [{"x":-0.21,"y":59.5}]},
		{ "id": "Jordan", "data": [{"x":2.05,"y":96.3}]},
		{ "id": "Kazakhstan", "data": [{"x":1.04,"y":86.1}]},
		{ "id": "Kenya", "data": [{"x":1.69,"y":31.9}]},
		{ "id": "Kiribati", "data": [{"x":1.13,"y":62.5}]},
		{ "id": "Korea, North", "data": [{"x":0.53,"y":45}]},
		{ "id": "Korea, South", "data": [{"x":0.48,"y":67.1}]},
		{ "id": "Kuwait", "data": [{"x":1.46,"y":100}]},
		{ "id": "Kyrgyzstan", "data": [{"x":1.05,"y":20.6}]},
		{ "id": "Laos", "data": [{"x":1.51,"y":1.1}]},
		{ "id": "Latvia", "data": [{"x":-1.08,"y":39.1}]},
		{ "id": "Lebanon", "data": [{"x":-1.1,"y":87.2}]},
		{ "id": "Lesotho", "data": [{"x":0.28,"y":0}]},
		{ "id": "Liberia", "data": [{"x":2.5,"y":63.3}]},
		{ "id": "Libya", "data": [{"x":1.58,"y":99.9}]},
		{ "id": "Lithuania", "data": [{"x":-1.08,"y":59.9}]},
		{ "id": "Luxembourg", "data": [{"x":1.98,"y":23.7}]},
		{ "id": "Macau", "data": [{"x":0.74,"y":100}]},
		{ "id": "Macedonia", "data": [{"x":0.17,"y":64.3}]},
		{ "id": "Madagascar", "data": [{"x":2.5,"y":73.9}]},
		{ "id": "Malawi", "data": [{"x":3.31,"y":5.8}]},
		{ "id": "Malaysia", "data": [{"x":1.37,"y":82.1}]},
		{ "id": "Maldives", "data": [{"x":-0.06,"y":96.2}]},
		{ "id": "Mali", "data": [{"x":3.02,"y":67.8}]},
		{ "id": "Malta", "data": [{"x":0.26,"y":88.5}]},
		{ "id": "Marshall Islands", "data": [{"x":1.55,"y":80.8}]},
		{ "id": "Mauritania", "data": [{"x":2.17,"y":63.8}]},
		{ "id": "Mauritius", "data": [{"x":0.59,"y":66.3}]},
		{ "id": "Mexico", "data": [{"x":1.12,"y":72.2}]},
		{ "id": "Micronesia, Federated States of", "data": [{"x":-0.52,"y":96}]},
		{ "id": "Moldova", "data": [{"x":-1.05,"y":85.7}]},
		{ "id": "Mongolia", "data": [{"x":1.18,"y":94.9}]},
		{ "id": "Montenegro", "data": [{"x":-0.28,"y":24.7}]},
		{ "id": "Montserrat", "data": [{"x":0.45,"y":100}]},
		{ "id": "Morocco", "data": [{"x":0.97,"y":67.5}]},
		{ "id": "Mozambique", "data": [{"x":2.46,"y":14}]},
		{ "id": "Namibia", "data": [{"x":1.95,"y":30.1}]},
		{ "id": "Nauru", "data": [{"x":0.53,"y":100}]},
		{ "id": "Nepal", "data": [{"x":1.16,"y":5.5}]},
		{ "id": "Netherlands", "data": [{"x":0.39,"y":80.4}]},
		{ "id": "New Caledonia", "data": [{"x":1.33,"y":78.4}]},
		{ "id": "New Zealand", "data": [{"x":0.79,"y":23.8}]},
		{ "id": "Nicaragua", "data": [{"x":0.98,"y":59}]},
		{ "id": "Niger", "data": [{"x":3.19,"y":96.1}]},
		{ "id": "Nigeria", "data": [{"x":2.43,"y":80.3}]},
		{ "id": "Niue", "data": [{"x":-0.03,"y":100}]},
		{ "id": "Norway", "data": [{"x":1.01,"y":4.1}]},
		{ "id": "Oman", "data": [{"x":2.03,"y":100}]},
		{ "id": "Pakistan", "data": [{"x":1.43,"y":61.8}]},
		{ "id": "Panama", "data": [{"x":1.27,"y":35.8}]},
		{ "id": "Papua New Guinea", "data": [{"x":1.71,"y":62.1}]},
		{ "id": "Paraguay", "data": [{"x":1.18,"y":0.2}]},
		{ "id": "Peru", "data": [{"x":0.95,"y":62.6}]},
		{ "id": "Philippines", "data": [{"x":1.57,"y":68.9}]},
		{ "id": "Poland", "data": [{"x":-0.13,"y":77.7}]},
		{ "id": "Portugal", "data": [{"x":0.04,"y":37.9}]},
		{ "id": "Puerto Rico", "data": [{"x":-1.74,"y":94.8}]},
		{ "id": "Qatar", "data": [{"x":2.27,"y":99.5}]},
		{ "id": "Romania", "data": [{"x":-0.33,"y":46.7}]},
		{ "id": "Russia", "data": [{"x":-0.08,"y":70.2}]},
		{ "id": "Rwanda", "data": [{"x":2.45,"y":27.6}]},
		{ "id": "Saint Helena, Ascension, and Tristan da Cunha", "data": [{"x":0.18,"y":100}]},
		{ "id": "Saint Kitts and Nevis", "data": [{"x":0.73,"y":94.9}]},
		{ "id": "Saint Lucia", "data": [{"x":0.32,"y":98.9}]},
		{ "id": "Saint Pierre and Miquelon", "data": [{"x":-1.08,"y":97.8}]},
		{ "id": "Saint Vincent and the Grenadines", "data": [{"x":-0.25,"y":83.3}]},
		{ "id": "Samoa", "data": [{"x":0.6,"y":66.7}]},
		{ "id": "Sao Tome and Principe", "data": [{"x":1.72,"y":80}]},
		{ "id": "Saudi Arabia", "data": [{"x":1.45,"y":99.9}]},
		{ "id": "Senegal", "data": [{"x":2.39,"y":88.5}]},
		{ "id": "Serbia", "data": [{"x":-0.46,"y":59}]},
		{ "id": "Seychelles", "data": [{"x":0.77,"y":92}]},
		{ "id": "Sierra Leone", "data": [{"x":2.38,"y":33.3}]},
		{ "id": "Singapore", "data": [{"x":1.82,"y":97.1}]},
		{ "id": "Slovakia", "data": [{"x":-0.01,"y":35.1}]},
		{ "id": "Slovenia", "data": [{"x":-0.31,"y":31.8}]},
		{ "id": "Solomon Islands", "data": [{"x":1.94,"y":97.3}]},
		{ "id": "Somalia", "data": [{"x":2,"y":98.8}]},
		{ "id": "South Africa", "data": [{"x":0.99,"y":86.7}]},
		{ "id": "South Sudan", "data": [{"x":3.83,"y":100}]},
		{ "id": "Spain", "data": [{"x":0.78,"y":45.1}]},
		{ "id": "Sri Lanka", "data": [{"x":0.76,"y":55.3}]},
		{ "id": "Sudan", "data": [{"x":1.64,"y":34.4}]},
		{ "id": "Suriname", "data": [{"x":1.02,"y":54.7}]},
		{ "id": "Sweden", "data": [{"x":0.81,"y":6.3}]},
		{ "id": "Switzerland", "data": [{"x":0.69,"y":2.9}]},
		{ "id": "Taiwan", "data": [{"x":0.17,"y":75.4}]},
		{ "id": "Tajikistan", "data": [{"x":1.62,"y":7}]},
		{ "id": "Tanzania", "data": [{"x":2.75,"y":46}]},
		{ "id": "Thailand", "data": [{"x":0.3,"y":76.7}]},
		{ "id": "Togo", "data": [{"x":2.64,"y":69.9}]},
		{ "id": "Tonga", "data": [{"x":-0.05,"y":82.4}]},
		{ "id": "Trinidad and Tobago", "data": [{"x":-0.2,"y":99.6}]},
		{ "id": "Tunisia", "data": [{"x":1.01,"y":93.4}]},
		{ "id": "Turkey", "data": [{"x":0.52,"y":56.8}]},
		{ "id": "Turkmenistan", "data": [{"x":1.12,"y":100}]},
		{ "id": "Turks and Caicos Islands", "data": [{"x":2.16,"y":100}]},
		{ "id": "Tuvalu", "data": [{"x":0.85,"y":96}]},
		{ "id": "Uganda", "data": [{"x":3.2,"y":14.8}]},
		{ "id": "Ukraine", "data": [{"x":-0.41,"y":62.1}]},
		{ "id": "United Arab Emirates", "data": [{"x":2.37,"y":99.5}]},
		{ "id": "United Kingdom", "data": [{"x":0.52,"y":55.6}]},
		{ "id": "United States", "data": [{"x":0.81,"y":70.6}]},
		{ "id": "Uruguay", "data": [{"x":0.27,"y":34.7}]},
		{ "id": "Uzbekistan", "data": [{"x":0.93,"y":86.4}]},
		{ "id": "Vanuatu", "data": [{"x":1.85,"y":81.8}]},
		{ "id": "Venezuela", "data": [{"x":1.24,"y":52.8}]},
		{ "id": "Vietnam", "data": [{"x":0.93,"y":55}]},
		{ "id": "Virgin Islands", "data": [{"x":-0.25,"y":13.9}]},
		{ "id": "West Bank", "data": [{"x":1.84,"y":92.1}]},
		{ "id": "Western Sahara", "data": [{"x":2.7,"y":100}]},
		{ "id": "Yemen", "data": [{"x":2.28,"y":99}]},
		{ "id": "Zambia", "data": [{"x":2.93,"y":0.3}]},
		{ "id": "Zimbabwe", "data": [{"x":1.56,"y":58}]}
		]}
	        margin={{
	            "top": 60,
	            "right": 140,
	            "bottom": 70,
	            "left": 90
	        }}
	        xScale={{
	            "type": "linear",
	            "min": 0,
	            "max": "auto"
	        }}
	        yScale={{
	            "type": "linear",
	            "min": 0,
	            "max": "auto"
	        }}
	        axisTop={null}
	        axisRight={null}
	        axisBottom={{
	            "orient": "bottom",
	            "tickSize": 5,
	            "tickPadding": 5,
	            "tickRotation": 0,
	            "legend": "% Annual Population Growth",
	            "legendPosition": "middle",
	            "legendOffset": 46
	        }}
	        axisLeft={{
	            "orient": "left",
	            "tickSize": 5,
	            "tickPadding": 5,
	            "tickRotation": 0,
	            "legend": "Percent Power from Fossil Fuels",
	            "legendPosition": "middle",
	            "legendOffset": -60
	        }}
	        animate={true}
	        motionStiffness={90}
	        motionDamping={15}
	        legends={[
	            {
	                "anchor": "bottom-right",
	                "direction": "column",
	                "translateX": 130,
	                "itemWidth": 100,
	                "itemHeight": 12,
	                "itemsSpacing": 5,
	                "itemTextColor": "#000",
	                "symbolSize": 16,
	                "symbolShape": "diamond",
	                "colors": "paired",
					"colorBy": "id",
	                "effects": [
	                    {
	                        "on": "hover",
	                        "style": {
	                            "itemTextColor": "#f00",
	                			"colors": "paired",
								"colorBy": "id"
	                        }
	                    }
	                ]
	            }
	        ]}
	    />
		);
	}
}
export default PopGrowthVsFossilPower
